module.exports = {
	// 主色
	primary: '#BC9D6F',
	primaryHover: '#ecc48c',
	primaryPlainHover: '#ecc48c',
	primaryColor: '#ffffff',
	primaryColorPlain: '#BC9D6F',
	primaryDisabled: '#ecc48c',
	// 默认
	'default': '#f8f8f8',
	defaultHover: '#F2F2F2',
	defaultPlainHover: '#F2F2F2',
	defaultColor: '#000000',
	defaultColorPlain: '#000000',
	defaultDisabled: '#F2F2F2',
	// 成功
	success: '#67C23A',
	successHover: '#b3e19d',
	successPlainHover: '#b3e19d',
	successColor: '#ffffff',
	successColorPlain: '#67C23A',
	successDisabled: '#b3e19d',
	// 警告
	warning: '#FFBF00',
	warningHover: '#f3d19e',
	warningPlainHover: '#f3d19e',
	warningColor: '#ffffff',
	warningColorPlain: '#FFBF00',
	warningDisabled: '#f3d19e',
	// 危险
	danger: '#FF6010',
	dangerHover: '#fab6b6',
	dangerPlainHover: '#fab6b6',
	dangerColor: '#ffffff',
	dangerColorPlain: '#FF6010',
	dangerDisabled: '#fab6b6',
}